Crop width and height dimensions returned by hook
bundlesandbatches/next-sanity-image pull request #25
Opened 2021-11-12 06:49 UTC by gpoole

Automatically adjusts the `width` and `height` dimensions returned from `useNextSanityImage` for images with a `crop` present.

I believe the hotspot component should be [automatically handled by @sanity/image-url](https://github.com/sanity-io/image-url#builder-methods) and it isn't necessary to touch it here.

I had to fix an unrelated failing test to get them working (using `DEFAULT_FALLBACK_IMAGE_WIDTH` which is not defined), I'm not sure if I missed something there.

Fixes #22

2021-11-17 12:42 UTC, RobEasthope commented
@gpoole Thanks for the work on this.

@lorenzodejong This PR is a bit critical for my current project. Is the ready to go and if not, is there anything I can do to help such as testing the edge cases mentioned in the ticket?

2021-11-17 13:29 UTC, lorenzodejong commented
Great work on the PR, i'll take a look at this with my test project. @RobEasthope if you want you can also test the scenario's in your project by checking out this PR locally.

2021-11-17 13:39 UTC, lorenzodejong requested changes

2021-11-17 13:39 UTC, lorenzodejong commented on src/useNextSanityImage.ts
>  			return (
Perhaps we should also pass the croppedImageDimensions to the imageBuilder callback, so it can be used to modify the image further.

2021-11-17 13:39 UTC, lorenzodejong commented on src/useNextSanityImage.ts
> +		const croppedImageDimensions = getCroppedDimensions(image);
It might be better to pass the `originalImageDimensions` to `getCroppedDimensions` to prevent calculating the original/base dimensions twice.

2021-11-17 13:41 UTC, lorenzodejong commented on src/useNextSanityImage.ts
>  			return (
Make sure to also modify the `UseNextSanityImageBuilderOptions` and `UseNextSanityBlurUpImageBuilderOptions` types.

2021-11-17 22:02 UTC, RobEasthope commented
> Great work on the PR, i'll take a look at this with my test project. @RobEasthope if you want you can also test the scenario's in your project by checking out this PR locally.

Will do @lorenzodejong

2021-11-18 09:09 UTC, lorenzodejong commented
I've done some testing in my project and have not found an unsupported edge case. If we can fix the requested changes we can get this PR integrated.

2021-11-18 09:23 UTC, gpoole commented
Thanks for the feedback, hopefully should all be addressed now @lorenzodejong.

2021-11-24 16:08 UTC, lorenzodejong approved these changes

2021-11-24 16:08 UTC, merged

2021-11-24 16:18 UTC, lorenzodejong commented
Version 3.2.0 has just been released with this feature. Thanks for the contribution @gpoole, great work!

2021-11-25 11:57 UTC, lorenzodejong commented
Version 3.2.0 included an incorrect build by my mistake, i've just released 3.2.1 which fixes this. I will implement a Github Action for releasing in the future to prevent these kinds of mistakes from happening...

2021-11-30 00:13 UTC, gpoole commented
Thanks @lorenzodejong and thanks for this hook, saved me a lot of time!